### ISSUE TITLE
Add ecukes support back in?

### ISSUE THREAD

**Issue by timvisher** [timvisher/vimgolf.el#1]
@echosa I'm actually unfamiliar with ecukes. If you want you can revert the commit the removed them and add instructions for running them to the CONTRIBUTING doc.

If not feel free to close this issue. :)

**Comment by timvisher** [comment]
I don't know where unit testing for elisp is right now but I don't think ecukes is the answer we were looking for.

**Comment by echosa** [comment]
:+1:
