### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by bennyandresen** [timvisher/vimgolf.el#4]
This project is currently lacking a clearly stated free license.

Please consider adding one. :-)

Reference: https://github.com/emacsmirror/epkg-reports/blob/master/licenses-details.org

**Comment by antonalekseev** [comment]
Unfortunately vimgolf.el was removed from MELPA (https://github.com/melpa/melpa/issues/5498) due to this issue. Any chance to resolve this issue and get it back there?

**Comment by timvisher** [comment]
Fixed by https://github.com/timvisher/vimgolf.el/commit/d6917c74c5dd030920bab3cb6d563c20f3bac1d7
