### ISSUE TITLE
Package not in melpa

### ISSUE THREAD

**Issue by fowlie** [timvisher/vimgolf.el#5]
I wanted to install this package but can't find it: https://melpa.org/#/?q=vimgolf

Why is it gone?

**Comment by timvisher** [comment]
The issue was a lack of license. Fixed in #4.

**Comment by timvisher** [comment]
Well I guess technically it will be fixed by https://github.com/melpa/melpa/pull/6599 :)

**Comment by timvisher** [comment]
https://melpa.org/#/vimgolf
https://stable.melpa.org/#/vimgolf

♪♪ ヽ(ˇ∀ˇ )ゞ
